### ISSUE TITLE
Missing sensors 

### ISSUE THREAD

**Issue by BFipsen** [benct/lovelace-xiaomi-vacuum-card#111]
Hi, i have big troubles, brush, filter and other sensors are unawailable.

I see the problem with my xiaomi mijia V2 and V8
![image](https://user-images.githubusercontent.com/47211841/207450825-a7573075-9ff8-49a2-918f-33822b216ba9.png)

Thanks in advance

**Comment by ualex73** [comment]
I got the same issue with my Xiaomi (Roborock S5x)

**Comment by flens74** [comment]
same issue with Dreame D9 Max

**Comment by Camposmansi** [comment]
Now it happens to me. Solution?

**Comment by LaurisGale** [comment]
Same here with Roborock S5x and I'm using Roborock extension. Xiaomi addon did not have this problem

**Comment by AzzMG** [comment]
One and a half year later I decided to try out this custom-card and facing the same issue as all of you, but with a Roborock S6

**Comment by Scope666** [comment]
Same:  Q5 Max+

**Comment by sir106** [comment]
same here

**Comment by Scope666** [comment]
For now, I got my Roborock working by doing this:

```
type: custom:xiaomi-vacuum-card
entity: vacuum.roborock_q5_max
vendor: xiaomi
image: /local/vacuum.png
attributes:
  main_brush:
    key: main_brush_time_left
  side_brush:
    key: side_brush_time_left
  filter:
    key: filter_time_left
  sensor:
    key: sensor_time_left
state:
  cleaning_time:
    key: cleaning_time
    label: "Last Clean time: "
    unit: " minutes"
```
<img width="469" alt="image" src="https://github.com/user-attachments/assets/bcf07cf6-7376-42ed-a49f-21e5f9aa564a">
