### ISSUE TITLE
Feature Request: ability to add ANY entity state to 'Attributes'

### ISSUE THREAD

**Issue by Kagey-cmd** [benct/lovelace-xiaomi-vacuum-card#118]
My use case:
I have a input_datetime entity that updates each time a vacuum's state changes to cleaning. It allows me to quickly see when the last time my Roomba did its thing. I'd like to be able to display this timestamp on the xiaomi-vacuum-card.

```
attributes:
  bin_full:
    key: bin_full
    label: 'Bin Full: '
  last_cleaned:
    label: 'Last Cleaned: '
    entity_id: input_datetime.roomba_last_cleaned
  bin_present: false
```
