### ISSUE TITLE
not working with 0.106

### ISSUE THREAD

**Issue by Schluggi** [benct/lovelace-xiaomi-vacuum-card#32]
Hi,

in 0.106 some changes happend to customs cards: https://developers.home-assistant.io/blog/2020/02/18/106-custom-card-changes/

After upgrading from 0.105 to 0.106 i got this error in the ui:
```
can't define property "service": Object is not extensible

type: 'custom:xiaomi-vacuum-card'
entity: vacuum.sucker
name: Sucker
image: false
buttons: true
labels:
  status: Status
  battery: Batterie
  mode: Modus
  main_brush: Main Brush
  side_brush: Side Brush
  filter: Filter
  sensor: Sensor
```
