### ISSUE TITLE
Add support for Xiaomi STYJ02YM Vacuum

### ISSUE THREAD

**Issue by mredone** [benct/lovelace-xiaomi-vacuum-card#34]
Is any chance to add right side of brushes status on card?

Here is dev status for entity:

```
fan_speed_list:
  - Silent
  - Standard
  - Medium
  - Turbo
battery_level: 100
battery_icon: 'mdi:battery-charging-100'
fan_speed: Turbo
run_state: 5
mode: 0
err_state: 2105
battary_life: 100
box_type: 1
mop_type: 0
s_time: 0
s_area: 1.42
suction_grade: 3
water_grade: 12
remember_map: 1
has_map: 1
is_mop: 0
has_newmap: 0
side_brush_hours: 178
main_brush_hours: 358
hypa_hours: 178
mop_hours: 180
status: docked
friendly_name: Wariat
supported_features: 13180
```

I try add a new vendor to your js file but it not work
I try change :
```
            const attributes = {
                status: 'status',
                battery: 'battery_level',
                mode: 'fan_speed',
                main_brush: 'main_brush_left',
                side_brush: 'side_brush_left',
                filter: 'filter_left',
                sensor: 'sensor_dirty_left',
            };
```
To

```
            const attributes = {
                status: 'status',
                battery: 'battery_level',
                mode: 'fan_speed',
                main_brush: 'main_brush_hours',
                side_brush: 'side_brush_hours',
                filter: 'hypa_hours',
                sensor: 'sensor_dirty_left',
            };
```
But it not work

Sorry for my English

Regards
Ed

**Comment by nhok3296** [comment]
I have the same problem

**Comment by nhok3296** [comment]
You can add this to the lovelace configuration
```
buttons:
  locate: false
  pause: false
  start: true
  stop: true
entity: vacuum.xiaomi_vacuum_cleaner_styj02ym
image: /local/img/vacuum.png
labels:
  battery: Pin
  filter: Lọc bụi
  main_brush: Chổi chính
  mode: Chế độ hút
  sensor: Lọc nước
  side_brush: Chổi phụ
  status: Trạng thái
attributes:
  filter: hypa_hours
  main_brush: main_brush_hours
  sensor: mop_hours
  side_brush: side_brush_hours
name: false
type: 'custom:xiaomi-vacuum-card'
vendor: xiaomi
```
