### ISSUE TITLE
[Feature request] Add button to send vacuumer to location of trashbin.

### ISSUE THREAD

**Issue by palengh** [benct/lovelace-xiaomi-vacuum-card#41]
I really appreciate the job you put into this. I set up my Xiaome Roborock S52 today, and was missing one, to me, essential function; send the vacuumer to a spot where the basket can be emptied.

So i hope for a small change, adding button and icon for `trash`, and then a space in config where I can set the position for the target.

I do have my own script for this, but it would be neat to embed it all in your slick ad-on.
```
vacuum_move_to_dustbin:
  alias: "Flytt til søpledunk"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.albertinne
        command: app_goto_target
        params: [43000,28500]
```

```
type: 'custom:xiaomi-vacuum-card'
name: Albertinne
vendor: xiaomi
entity: vacuum.albertinne
image: /local/images/albertinne.jpg
buttons:
  locate: true
  start: true
  stop: true
  trash: true
icons:
  start: 'mdi:play'
  stop: 'mdi:stop'
  trash: 'mdi:trash-can-outline'
trash_position: '[43000,28500]'
```
