### ISSUE TITLE
Attributes on Valetudo 2021.03.0

### ISSUE THREAD

**Issue by micdis** [benct/lovelace-xiaomi-vacuum-card#72]
Hi!
since I updated my Valetudos to 2021.03.0 I don't see the attributes anymore.
They come over MQTT (sensor.main_brush), but in the Lovelace Card I only see N/A

Am I doing something wrong? 

```
entity: vacuum.rockrobo
type: 'custom:xiaomi-vacuum-card'
vendor: valetudo
name: false
attributes:
  main_brush:
    key: sensor.main_brush
```

**Comment by Dinth** [comment]
Same issue here. Before Valetudo was posting brushes status as attributes to vacuum.* entity, now it posts that data as separate entities and i cannot get them to show in the card

**Comment by dckiller51** [comment]
Hello,
You can put the valutedo re. no problem with.
https://github.com/rand256/valetudo

**Comment by cnopix** [comment]
Hello,

i have the same error :(

how can i resolve without change to valetudo RE ?

Cnopix.

**Comment by matejzero** [comment]
This seems to be changed in Valetudo 2021.04.0 with the rework of MQTT to better support Homie integration.

Is there any chance to add support to read state from custom sensor and not only attributes?

**Comment by benct** [comment]
Support for default sensor data has been added to version `4.4.0`, but only tested for `xiaomi` vacuums. Let me know if it works for you or not.

**Comment by gervaso** [comment]
Hi,
it works, you just need to rename the keys in the following way.
```
type: custom:xiaomi-vacuum-card
entity: vacuum.cinesino
vendor: valetudo
attributes:
  main_brush:
    key: main_brush
  side_brush:
    key: right_brush
  filter:
    key: main_filter
  sensor:
    key: sensor_cleaning
```
My sensors are named "sensor.cinesino_main_brush", "sensor.cinesino_right_brush" and so on.
