### ISSUE TITLE
Missing buttons icons

### ISSUE THREAD

**Issue by adizag** [benct/lovelace-xiaomi-vacuum-card#75]
As can be seen in the image, all the action buttons are missing, and pressing on the halo does nothing.
tried to uninstall, reinstall.... no help

Tnx!

![image](https://user-images.githubusercontent.com/17390016/121405367-a14d2700-c965-11eb-9812-243d13024272.png)

**Comment by dckiller51** [comment]
You must follow this provision
```
- type: custom:xiaomi-vacuum-card
  entity: vacuum.xiaomi_vacuum_cleaner
  buttons:
    start:
      service:
```
