### ISSUE TITLE
Show attributes based on state possible?

### ISSUE THREAD

**Issue by X1pheR** [benct/lovelace-xiaomi-vacuum-card#78]
Great minimalistic card! As a nice finish I tried adding custom attributes per the instructions and it works nicely. But would it be possible to only show things based on the state? For example below to show the cleaned area. But if it's not running it doesn't make sense to show it. Also for buttons. It doesn't make sense to show a stop button for example if it is docked.

```
- type: custom:xiaomi-vacuum-card
  entity: vacuum.xiaomi_vacuum_cleaner
  attributes:
    clean_area:
      key: 'clean_area'
      label: 'Cleaned area: '
      unit: ' m2'
```
