### ISSUE TITLE
Certain attributes show as unavailable since HA update 2021.11

### ISSUE THREAD

**Issue by TTLucian** [benct/lovelace-xiaomi-vacuum-card#89]
Certain attributes show as unavailable on the card. The sensors are enabled and working.
mop_attached
water_box_attached
I think this happens because they are binary_sensors and currently the card only reads "sensor" values, but not "binary_sensor" values.

**Comment by dizzad** [comment]
Same for me
Update to 4.4.0 right now
![image](https://user-images.githubusercontent.com/65437972/140652537-38bf89c0-4e1a-414a-88dd-865804ed2f83.png)

**Comment by benct** [comment]
Have look at #84, things changed in 2021.11.0. The binary sensors are not supported as of now, I'll see if I can do something about that soon.

If the card still does not work, try [this](https://github.com/benct/lovelace-xiaomi-vacuum-card/issues/84#issuecomment-962684848).

**Comment by TTLucian** [comment]
Thanks. I've seen [#84](https://github.com/benct/lovelace-xiaomi-vacuum-card/issues/84). Card works for ok "sensor" state but not for "binary_sensor" state (like mop_attached and water_box_attached).
As a workaround, template sensors can be manually created with binary_sensor state, like so:

```yaml
template:
  - sensor:
      name: Robot Mop Attached
      unique_id: sensor.robot_mop_attached
      state: >
        {% if is_state('binary_sensor.robot_mop_attached', 'off') %}
        No
        {% elif is_state('binary_sensor.robot_mop_attached', 'on') %}
        Yes
        {% endif %}
      availability: >
        {% if is_state('vacuum.robot', 'unavailable') %}
          false
        {% else %}
          true
        {% endif %}
      icon: >
        {% if is_state('binary_sensor.robot_water_box_attached', 'on') %}
          mdi:square
        {% else %}
          mdi:square-off
        {% endif %}

  - sensor:
      name: Robot Water Box Attached
      unique_id: sensor.robot_water_box_attached
      state: >
        {% if is_state('binary_sensor.robot_water_box_attached', 'off') %}
        No
        {% elif is_state('binary_sensor.robot_water_box_attached', 'on') %}
        Yes
        {% endif %}
      availability: >
        {% if is_state('vacuum.robot', 'unavailable') %}
          false
        {% else %}
          true
        {% endif %}
      icon: >
        {% if is_state('binary_sensor.robot_water_box_attached', 'on') %}
          mdi:water
        {% else %}
          mdi:water-off
        {% endif %}
```

```yaml
  - type: custom:xiaomi-vacuum-card
    entity: vacuum.robot
    name: Robot
    vendor: xiaomi
    image: /local/community/lovelace-xiaomi-vacuum-card/vacuum.png
    attributes:
      main_brush:
        key: main_brush_left
      side_brush:
        key: side_brush_left
      filter:
        key: filter_left
      sensor:
        key: sensor_dirty_left
      mop_attached:
        label: 'Mop attached: '
        key: mop_attached
      water_box_attached:
        label: 'Water box attached: '
        key: water_box_attached
```

Result:
![Untitled](https://user-images.githubusercontent.com/1855276/140663989-47e1a827-985c-421d-b550-5d874d59f1cb.jpg)
