### ISSUE TITLE
Ecovacs Deebot - State is stored in a different way

### ISSUE THREAD

**Issue by illuzn** [benct/lovelace-xiaomi-vacuum-card#96]
I have an Ecovacs Deebot Ozmo 920.

This device stores is current state directly in the state of vacuum.vacuum name e.g.

![image](https://user-images.githubusercontent.com/57167030/150286466-543803c8-5297-49bc-9700-9e2a602bb999.png)

I'm a complete noob so I am probably missing something but I'm not sure how to configure this card so this works.

**Comment by benct** [comment]
Does your vacuum entity have any attributes? (see `<your-ha-url>/developer-tools/state`)
Have you enabled sensors from the vacuum integration? (check entities under the integration on `/config/integrations`)
Check that you have followed the HA docs for your specific vacuum integration, etc.

**Comment by SmartHomeNewbie** [comment]
Hello, i seem to be having the same issue.
The vaccum entity does not have brush, filter and sensors attributes, they have their own entity.
"sensor.robotski_life_span_brush" is my main brush.
![vacuum](https://user-images.githubusercontent.com/75638271/159801780-4c081c33-56f5-44d1-8479-ab12180260b2.png)

EDIT: let me add that i have an Ecovacs Deebot T8 Aivi

**Comment by alberanid** [comment]
can confirm for an Ecovacs OZMO 920:
![Screenshot from 2022-05-15 18-27-59](https://user-images.githubusercontent.com/222857/168483304-4694fd18-b1d9-4b52-a0d3-778ed4b58d97.png)

On the development page:

State: `cleaning` (while running)

State attributes:

```
fan_speed_list:
  - quiet
  - normal
  - max
  - max+
battery_level: 67
battery_icon: mdi:battery-70
fan_speed: max
rooms:
  laundry: 0
  lounge: 1
  bedroom: 2
  bathroom: 3
  study: 10
last_error: 'NoError: Robot is operational (0)'
friendly_name: vacuum
supported_features: 15228
```

All sensors are enabled.

I'm using this integration: https://github.com/DeebotUniverse/Deebot-4-Home-Assistant

My card configuration:
```
type: custom:xiaomi-vacuum-card
entity: vacuum.my_vacuum
vendor: ecovacs
attributes:
  main_brush: false
  side_brush: false
  filter: false
  sensor: false
buttons:
  spot: false
```
